// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdfvnzyuiyogcmqybizj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkZnZuenl1aXlvZ2NtcXliaXpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMjY3MDIsImV4cCI6MjA3MzkwMjcwMn0.Y_0PtmIMUUXEzINAZyZw2AXM0cLdhNJJc4L4ukPRU9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});