// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsitjsssiooebaonnheg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzaXRqc3NzaW9vZWJhb25uaGVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MDY2NDQsImV4cCI6MjA3MzA4MjY0NH0.ZucFp9uBnheFBRl2VBwu2kKtB-ufTAo7ppsdVT2uLe8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});